import type { Metadata } from "next";
import { sofia, sofia_italic, specialElite } from "@/_fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sofia.variable} ${sofia_italic.variable} ${specialElite.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
