import type { Metadata } from "next";
import { spaceGrotesk } from "@/_fonts/fonts";

import "./globals.css";
import "./colors.css";
import "./page.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceGrotesk.variable}>
      <body>{children}</body>
    </html>
  );
}
